<a href="https://colab.research.google.com/github/omj3424/python_suanLab/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기


---

강의 링크: https://youtu.be/lG8pEwvYwCw?si=V_CiAQBiom6dn0fL



---



## Pandas 란?

* 관계 또는 레이블링 데이터를 쉽고 직관적으로 작업할 수 있도록 고안된 빠르고 유연하며 표현력이 뛰어난 데이터 구조를 제공하는 Python 패키지

## Pandas 특징

* 부동 소수점이 아닌 데이터 뿐만 아니라 부동 소수점 데이터에서도 결측 데이터(NaN으로 표시됨)를 쉽게 처리
* 크기 변이성(Size mutability): DataFrame 및 고차원 객체에서 열을 삽입 및 삭제 가능
* 자동 및 명시적(explicit) 데이터 정렬: 객체를 라벨 집합에 명시적으로 정렬하거나, 사용자가 라벨을 무시하고 Series, DataFrame 등의 계산에서 자동으로 데이터 조정 가능
* 데이터 세트에서 집계 및 변환을 위한 분할(split), 적용(apply), 결합(combine) 작업을 수행할 수 있는 강력하고 유연한 group-by 함수 제공
* 누락된 데이터 또는 다른 Python 및 NumPy 데이터 구조에서 서로 다른 인덱싱 데이터를 DataFrame 개체로 쉽게 변환
* 대용량 데이터 세트의 지능형 라벨 기반 슬라이싱, 고급 인덱싱 및 부분 집합 구하기 가능
* 직관적인 데이터 세트 병합 및 결합
* 데이터 세트의 유연한 재구성 및 피벗
* 축의 계층적 라벨링(눈금당 여러 개의 라벨을 가질 수 있음)
* 플랫 파일(CSV 및 구분), Excel 파일, 데이터베이스 로딩 및 초고속 HDF5 형식의 데이터 저장/로드에 사용되는 강력한 IO 도구
* 시계열 특정 기능: 날짜 범위 생성 및 주파수 변환, 무빙 윈도우(moving window) 통계, 날짜 이동 및 지연

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'2.1.4'

## Pandas 객체


### Series 객체

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [ ]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s[1]

0.25

In [ ]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['c']

0.5

In [ ]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
'b' in s

True

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s[4]

0.25

In [ ]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
Name: count, dtype: int64

In [ ]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [ ]:
pop_tuple = {'서울특별시': 9720846,
             '부산광역시': 3404423,
             '인천광역시': 2947217,
             '대구광역시': 2427954,
             '대전광역시': 1471040,
             '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [ ]:
population['서울특별시']

9720846

In [ ]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [ ]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
pd.DataFrame(np.random.rand(5, 5),
             columns=['A', 'B', 'C', 'D', 'E'],
             index=[1, 2, 3, 4, 5])

A         B         C         D         E
1  0.938321  0.586249  0.019545  0.552771  0.699036
2  0.698161  0.072820  0.784336  0.236763  0.340728
3  0.786624  0.629472  0.491277  0.933174  0.805683
4  0.725665  0.770752  0.414387  0.855555  0.061230
5  0.050961  0.893332  0.204584  0.745087  0.030464

In [ ]:
male_tuple = {'서울특별시': 4732275,
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [ ]:
female_tuple = {'서울특별시': 4988571,
              '부산광역시': 1735805,
              '인천광역시': 1470404,
              '대구광역시': 1229139,
              '대전광역시': 736599,
              '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [ ]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수': male,
                         '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [ ]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [ ]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체

* Index: 일반적인 Index 객체이며, NumPy 배열 형식으로 축의 이름 표현
* Int64Index: 정수 값을 위한 Index
* MultiIndex: 단일 축에 여러 단계 색인을 표현하는 계층적 Index 객체(튜플의 배열과 유사)
* DatetimeIndex: NumPy의 datetime64 타입으로 타임스탬프 저장
* PeriodIndex: 기간 데이터를 위한 Index

In [ ]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Index([2, 4, 6, 8, 10], dtype='int64')

In [ ]:
idx[1]

4

In [ ]:
idx[1:2:2]

Index([4], dtype='int64')

In [ ]:
idx[-1::]

Index([10], dtype='int64')

In [ ]:
idx[::2]

Index([2, 6, 10], dtype='int64')

In [ ]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

 * `append`: 색인 객체를 추가한 새로운 색인 반환
 * `difference`: 색인의 차집합 반환
 * `&` `intersection`: 색인의 교집합 반환
 * `|` `union`: 색인의 합집합 반환
 * `isin`: 색인이 존재하는지 여부를 불리언 배열로 반환
 * `delete`: 색인이 삭제된 새로운 색인 반환
 * `drop`: 값이 삭제된 새로운 색인 반환
 * `insert`: 색인이 추가된 새로운 색인 반환
 * `is_monotonic`: 색인이 단조성을 가지면 True
 * `is_unique`: 중복되는 색인이 없다면 True
 * `unique`: 색인에서 중복되는 요소를 제거하고 유일한 값만 반환

In [ ]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)

Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Index([1, 8], dtype='int64')
Index([-1, -2, -1, 0, 1], dtype='int64')
Index([2, 4, 6], dtype='int64')
Index([0, 0, 4, 6, 0], dtype='int64')
Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Index([3, 6, 5, 6, 15], dtype='int64')
Index([2, 4, 6, 8], dtype='int64')
Index([2, 4, 6, 8], dtype='int64')
Index([3, 6, 1, 0, 15], dtype='int64')




---



## 인덱싱(Indexing)

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['b']

0.25

In [ ]:
'b' in s

True

In [ ]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [ ]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [ ]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[(s > 0.4) & (s <0.8)]

c    0.50
d    0.75
dtype: float64

In [ ]:
s[['a', 'c', 'e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [ ]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [ ]:
s[1]

'a'

In [ ]:
s[2:4]

5    c
7    d
dtype: object

In [ ]:
s.iloc[1]

'b'

In [ ]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [ ]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [ ]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱

* `df[val]`: 하나의 컬럼 또는 여러 컬럼을 선택
* `df.loc[val]`: 라벨값으로 로우의 부분집합 선택
* `df.loc[:, val]`: 라벨값으로 컬럼의 부분집합 선택
* `df.loc[val1, val2]`: 라벨값으로 로우와 컬럼의 부분집합 선택
* `df.iloc[where]`: 정수 색인으로 로우의 부분집합 선택
* `df.iloc[:, where]`: 정수 색인으로 컬럼의 부분집합 선택
* `df.iloc[where_i, where_j]`: 정수 색인으로 로우와 컬럼의 부분집합 선택
* `df.at[label_i, label_j]`: 로우와 컬럼의 라벨로 단일 값 선택
* `df.iat[i, j]`: 로우와 컬럼의 정수 색인으로 단일 값 선택
* `reindex`: 하나 이상의 축을 새로운 색인으로 재색인
* `get_value, set_value`: 로우와 컬럼의 이름으로 값 선택

In [ ]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [ ]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [ ]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [ ]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [ ]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [ ]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [ ]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [ ]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [ ]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [ ]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[korea_df.남여비율 > 100]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [ ]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [ ]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [ ]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020),
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [ ]:
pop_tuples = [10312545, 9720846,
              3567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     3567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [ ]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [ ]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population[:, 2010]

서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [ ]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   3567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     3567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [ ]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   3567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [ ]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   3567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [ ]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [ ]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [ ]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.622899  0.751332  0.691711
  2  0.234333  0.384072  0.893880
b 1  0.241678  0.629621  0.925252
  2  0.660158  0.910690  0.455119
c 1  0.924346  0.316140  0.312700
  2  0.989291  0.640389  0.492868

In [ ]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
              codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                  names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.22 -0.16  0.40 -1.94 -0.44 -1.08
      2     -0.44 -0.73  0.74  0.27 -0.05 -0.72
b     1     -2.85 -1.48 -1.87 -1.29  0.77  0.88
      2     -0.71  0.75  0.66 -0.21  1.21  0.09
c     1      0.85 -1.35 -0.18  0.61  1.10  0.65
      2     -0.64 -0.35  0.08  0.83 -0.08  1.05

In [ ]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1      0.40 -1.94
      2      0.74  0.27
b     1     -1.87 -1.29
      2      0.66 -0.21
c     1     -0.18  0.61
      2      0.08  0.83

#### 인덱싱 및 슬라이싱

In [ ]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population['인천광역시', 2010]

2758296

In [ ]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
dtype: int64

In [ ]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [ ]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.22 -0.16  0.40 -1.94 -0.44 -1.08
      2     -0.44 -0.73  0.74  0.27 -0.05 -0.72
b     1     -2.85 -1.48 -1.87 -1.29  0.77  0.88
      2     -0.71  0.75  0.66 -0.21  1.21  0.09
c     1      0.85 -1.35 -0.18  0.61  1.10  0.65
      2     -0.64 -0.35  0.08  0.83 -0.08  1.05

In [ ]:
mdf['c2', 1]

name1  name2
a      1        0.40
       2        0.74
b      1       -1.87
       2        0.66
c      1       -0.18
       2        0.08
Name: (c2, 1), dtype: float64

In [ ]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -1.22 -0.16  0.40 -1.94
      2     -0.44 -0.73  0.74  0.27
b     1     -2.85 -1.48 -1.87 -1.29

In [ ]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1        0.40
       2        0.74
b      1       -1.87
       2        0.66
c      1       -0.18
       2        0.08
Name: (c2, 1), dtype: float64

In [ ]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.73  0.27 -0.72
b     2      0.75 -0.21  0.09
c     2     -0.35  0.83  1.05

#### 다중 인덱스 재정렬

In [ ]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [ ]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [ ]:
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  3567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [ ]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   3567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [ ]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     3.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
       2020  총인구수     3.404423e+06
             남자인구수    1.668618e+06
             여자인구수    1.735805e+06
             남여비율     9.612935e+01
서울특별시  2010  총인구수     1.031254e+07
             남자인구수    5.111259e+06
             여자인구수    5.201286e+06
             남여비율     9.826914e+01
       2020  총인구수     9.720846e+06
             남자인구수    4.732275e+06
             여자인구수    4.988571e+06
             남여비율     9.486234e+01
인천광역시  2010  총인구수     2.758296e+06
             남자인구수    1.390356e+06
             여자인구수    1.367940e+06
             남여비율     1.016387e+02
       2020  총인구수     2.947217e+06
             남자인구수    1.476813e+06
             여자인구수    1.470404e+06
             남여비율     1.004359e+02
dtype: float64

In [ ]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   3567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   3567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat.set_index(['행정구역', '년도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [ ]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    8
1    0
2    6
3    2
4    1
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  3  0  6
1  6  0  2
2  0  4  2

In [ ]:
np.exp(s)

0    2980.957987
1       1.000000
2     403.428793
3       7.389056
4       2.718282
dtype: float64

In [ ]:
np.cos(df * np.pi / 4)

A    B             C
0 -7.071068e-01  1.0 -1.836970e-16
1 -1.836970e-16  1.0  6.123234e-17
2  1.000000e+00 -1.0  6.123234e-17

In [ ]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                   columns=list('ACD'))
df1

A  C   D
0  6  4   5
1  3  1  15
2  5  1  11

In [ ]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns=list('BAECD'))
df2

B   A   E   C   D
0   7  19  13  19   1
1  10  18  19  10  15
2  10   1   9   2   3
3   6  13   9  11  16
4   6  18   5  15   3

In [ ]:
df1 + df2

A   B     C     D   E
0  25.0 NaN  23.0   6.0 NaN
1  21.0 NaN  11.0  30.0 NaN
2   6.0 NaN   3.0  14.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  25.000000  12.666667  23.000000   6.000000  18.666667
1  21.000000  15.666667  11.000000  30.000000  24.666667
2   6.000000  15.666667   3.000000  14.000000  14.666667
3  18.666667  11.666667  16.666667  21.666667  14.666667
4  23.666667  11.666667  20.666667   8.666667  10.666667

### 연산자 범용 함수

| Python 연산자 | Pandas 메소드 |
|-------------|-------------|
|`+`|`add`, `radd`|
|`-`|`sub`, `rsub`, `subtract`|
|`*`|`mul`, `rmul`, `multiply`|
|`/`|`truediv`, `div`, `rdiv`, `divide`|
|`//`|`floordiv`, `rfloordiv`|
|`%`|`mod`|
|`**`|`pow`, `rpow`|

#### add()

In [ ]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a + a[0]

array([[16,  4, 18],
       [16, 11, 15],
       [13,  6, 10]])

In [ ]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df + df.iloc[0]

A   B   C
0  16   4  18
1  16  11  15
2  13   6  10

In [ ]:
df.add(df.iloc[0])

A   B   C
0  16   4  18
1  16  11  15
2  13   6  10

#### sub() / subtract()

In [ ]:
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a - a[0]

array([[ 0,  0,  0],
       [ 0,  7, -3],
       [-3,  2, -8]])

In [ ]:
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  0  7 -3
2 -3  2 -8

In [ ]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  0  7 -3
2 -3  2 -8

In [ ]:
df.subtract(df['B'], axis=0)

A  B  C
0  6  0  7
1 -1  0 -3
2  1  0 -3

#### mul() / multply()




In [ ]:
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a * a[1]

array([[64, 18, 54],
       [64, 81, 36],
       [40, 36,  6]])

In [ ]:
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df * df.iloc[1]

A   B   C
0  64  18  54
1  64  81  36
2  40  36   6

In [ ]:
df.mul(df.iloc[1])

A   B   C
0  64  18  54
1  64  81  36
2  40  36   6

In [ ]:
df.multiply(df.iloc[2])

A   B  C
0  40   8  9
1  40  36  6
2  25  16  1

#### truediv() /  div() / divide() / floordiv()

In [ ]:
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.        , 4.5       , 0.66666667],
       [0.625     , 2.        , 0.11111111]])

In [ ]:
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df /df.iloc[0]

A    B         C
0  1.000  1.0  1.000000
1  1.000  4.5  0.666667
2  0.625  2.0  0.111111

In [ ]:
df.truediv(df.iloc[0])

A    B         C
0  1.000  1.0  1.000000
1  1.000  4.5  0.666667
2  0.625  2.0  0.111111

In [ ]:
df.div(df.iloc[1])

A         B         C
0  1.000  0.222222  1.500000
1  1.000  1.000000  1.000000
2  0.625  0.444444  0.166667

In [ ]:
df.divide(df.iloc[2])

A     B    C
0  1.6  0.50  9.0
1  1.6  2.25  6.0
2  1.0  1.00  1.0

In [ ]:
a // a[0]

array([[1, 1, 1],
       [1, 4, 0],
       [0, 2, 0]])

In [ ]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  4  0
2  0  2  0

#### mod()

In [ ]:
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a % a[0]

array([[0, 0, 0],
       [0, 1, 6],
       [5, 0, 1]])

In [ ]:
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  0  1  6
2  5  0  1

#### pow()

In [ ]:
a

array([[8, 2, 9],
       [8, 9, 6],
       [5, 4, 1]])

In [ ]:
a ** a[0]

array([[ 16777216,         4, 387420489],
       [ 16777216,        81,  10077696],
       [   390625,        16,         1]])

In [ ]:
df

A  B  C
0  8  2  9
1  8  9  6
2  5  4  1

In [ ]:
df.pow(df.iloc[0])

A   B          C
0  16777216   4  387420489
1  16777216  81   10077696
2    390625  16          1

In [ ]:
row = df.iloc[0, ::2]
row

A    8
C    9
Name: 0, dtype: int64

In [ ]:
df - row

A   B    C
0  0.0 NaN  0.0
1  0.0 NaN -3.0
2 -3.0 NaN -8.0

### 정렬(Sort)

In [ ]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [ ]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index=[2, 4, 1, 3],
                  columns=list('BDAC'))
df

B  D  A  C
2  8  7  8  1
4  5  4  7  2
1  3  1  3  8
3  2  0  3  1

In [ ]:
df.sort_index()

B  D  A  C
1  3  1  3  8
2  8  7  8  1
3  2  0  3  1
4  5  4  7  2

In [ ]:
df.sort_index(axis=1)

A  B  C  D
2  8  8  1  7
4  7  5  2  4
1  3  3  8  1
3  3  2  1  0

In [ ]:
df.sort_values(by='A')

B  D  A  C
1  3  1  3  8
3  2  0  3  1
4  5  4  7  2
2  8  7  8  1

In [ ]:
df.sort_values(by = ['A', 'C'])

B  D  A  C
3  2  0  3  1
1  3  1  3  8
4  5  4  7  2
2  8  7  8  1

### 순위(Ranking)

* `average`: 기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용
* `min`: 같은 값을 가지는 그룹을 낮은 순위로 지정
* `max`: 같은 값을 가지는 그룹을 높은 순위로 지정
* `first`: 데이터 내의 위치에 따라 순위 지정
* `dense`: 같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가

In [ ]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [ ]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [ ]:
s.rank(method='first')

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [ ]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [ ]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [ ]:
%timeit df1 +df2 +df3 + df4

160 ms ± 54.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit pd.eval('df1 + df2 + df3 + df4')

49.8 ms ± 684 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit df1 * -df2 / (-df3 + df4)

192 ms ± 5.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit pd.eval('df1 * -df2 / (-df3 + df4)')

59.3 ms ± 345 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

87.5 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

116 ms ± 24.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D','E'])
df.head()

A         B         C         D         E
0  0.743384  0.380778  0.558437  0.406521  0.146760
1  0.801741  0.559214  0.849034  0.922665  0.464356
2  0.597794  0.705840  0.392788  0.716413  0.431017
3  0.602767  0.896990  0.811697  0.511144  0.742347
4  0.723376  0.263707  0.004634  0.378022  0.977083

In [ ]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

28.2 ms ± 3.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

8.44 ms ± 415 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit df.eval('A + B / C - D * E')

23.1 ms ± 6.03 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
df.eval('R = A + B / C - D * E', inplace = True)
df.head()

A         B         C         D         E          R
0  0.743384  0.380778  0.558437  0.406521  0.146760   1.365586
1  0.801741  0.559214  0.849034  0.922665  0.464356   1.031944
2  0.597794  0.705840  0.392788  0.716413  0.431017   2.086006
3  0.602767  0.896990  0.811697  0.511144  0.742347   1.328401
4  0.723376  0.263707  0.004634  0.378022  0.977083  57.262722

In [ ]:
df.eval('R = A - B / C + D * E', inplace = True)
df.head()

A         B         C         D         E          R
0  0.743384  0.380778  0.558437  0.406521  0.146760   0.121182
1  0.801741  0.559214  0.849034  0.922665  0.464356   0.571539
2  0.597794  0.705840  0.392788  0.716413  0.431017  -0.890418
3  0.602767  0.896990  0.811697  0.511144  0.742347  -0.122866
4  0.723376  0.263707  0.004634  0.378022  0.977083 -55.815970

In [ ]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.136228
1         1.496499
2         0.923366
3         1.176447
4        -8.188148
            ...   
999995    0.099023
999996    0.650177
999997    0.326882
999998    0.127693
999999    0.215240
Length: 1000000, dtype: float64

In [ ]:
df.eval('A + @col_mean')

0         1.136228
1         1.496499
2         0.923366
3         1.176447
4        -8.188148
            ...   
999995    0.099023
999996    0.650177
999997    0.326882
999998    0.127693
999999    0.215240
Length: 1000000, dtype: float64

In [ ]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
12      0.406110  0.099173  0.880176  0.863666  0.429908  0.664733
13      0.219793  0.424912  0.717813  0.470136  0.506293 -0.134134
32      0.332894  0.449192  0.863421  0.484662  0.433191  0.022599
33      0.236622  0.340814  0.753746  0.239071  0.651303 -0.059830
40      0.418883  0.082213  0.697759  0.036264  0.828551  0.331104
...          ...       ...       ...       ...       ...       ...
999975  0.012571  0.292071  0.674786  0.077285  0.146084 -0.408975
999978  0.414437  0.062978  0.925035  0.562125  0.843808  0.820682
999980  0.092186  0.128261  0.598593  0.801408  0.020264 -0.105844
999994  0.453490  0.337796  0.609955  0.412828  0.620359  0.155787
999995  0.000091  0.282454  0.536289  0.271401  0.023559 -0.520197

[124917 rows x 6 columns]

In [ ]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
12      0.406110  0.099173  0.880176  0.863666  0.429908  0.664733
13      0.219793  0.424912  0.717813  0.470136  0.506293 -0.134134
32      0.332894  0.449192  0.863421  0.484662  0.433191  0.022599
33      0.236622  0.340814  0.753746  0.239071  0.651303 -0.059830
40      0.418883  0.082213  0.697759  0.036264  0.828551  0.331104
...          ...       ...       ...       ...       ...       ...
999975  0.012571  0.292071  0.674786  0.077285  0.146084 -0.408975
999978  0.414437  0.062978  0.925035  0.562125  0.843808  0.820682
999980  0.092186  0.128261  0.598593  0.801408  0.020264 -0.105844
999994  0.453490  0.337796  0.609955  0.412828  0.620359  0.155787
999995  0.000091  0.282454  0.536289  0.271401  0.023559 -0.520197

[124917 rows x 6 columns]

In [ ]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
12      0.406110  0.099173  0.880176  0.863666  0.429908  0.664733
13      0.219793  0.424912  0.717813  0.470136  0.506293 -0.134134
32      0.332894  0.449192  0.863421  0.484662  0.433191  0.022599
33      0.236622  0.340814  0.753746  0.239071  0.651303 -0.059830
40      0.418883  0.082213  0.697759  0.036264  0.828551  0.331104
...          ...       ...       ...       ...       ...       ...
999975  0.012571  0.292071  0.674786  0.077285  0.146084 -0.408975
999978  0.414437  0.062978  0.925035  0.562125  0.843808  0.820682
999980  0.092186  0.128261  0.598593  0.801408  0.020264 -0.105844
999994  0.453490  0.337796  0.609955  0.412828  0.620359  0.155787
999995  0.000091  0.282454  0.536289  0.271401  0.023559 -0.520197

[124917 rows x 6 columns]

In [ ]:
col_mean = df ['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
6       0.069859  0.370723  0.411804  0.122939  0.844097 -0.726611
10      0.017029  0.489345  0.272082  0.518466  0.136775 -1.710580
12      0.406110  0.099173  0.880176  0.863666  0.429908  0.664733
13      0.219793  0.424912  0.717813  0.470136  0.506293 -0.134134
18      0.021931  0.050711  0.018599  0.366311  0.449896 -2.539779
...          ...       ...       ...       ...       ...       ...
999980  0.092186  0.128261  0.598593  0.801408  0.020264 -0.105844
999982  0.047471  0.475854  0.311378  0.973572  0.309608 -1.179319
999994  0.453490  0.337796  0.609955  0.412828  0.620359  0.155787
999995  0.000091  0.282454  0.536289  0.271401  0.023559 -0.520197
999999  0.323672  0.096953  0.032639  0.841347  0.381038 -2.326241

[249671 rows x 6 columns]

In [ ]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
6       0.069859  0.370723  0.411804  0.122939  0.844097 -0.726611
10      0.017029  0.489345  0.272082  0.518466  0.136775 -1.710580
12      0.406110  0.099173  0.880176  0.863666  0.429908  0.664733
13      0.219793  0.424912  0.717813  0.470136  0.506293 -0.134134
18      0.021931  0.050711  0.018599  0.366311  0.449896 -2.539779
...          ...       ...       ...       ...       ...       ...
999980  0.092186  0.128261  0.598593  0.801408  0.020264 -0.105844
999982  0.047471  0.475854  0.311378  0.973572  0.309608 -1.179319
999994  0.453490  0.337796  0.609955  0.412828  0.620359  0.155787
999995  0.000091  0.282454  0.536289  0.271401  0.023559 -0.520197
999999  0.323672  0.096953  0.032639  0.841347  0.381038 -2.326241

[249671 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [ ]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [ ]:
def create_df(cols, idx):
  data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)

In [ ]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [ ]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [ ]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [ ]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [ ]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [ ]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [ ]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [ ]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [ ]:
#pd.concat([df1, df3], verify_integrity=True)

In [ ]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [ ]:
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [ ]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [ ]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [ ]:
df5.append(df6)

AttributeError: 'DataFrame' object has no attribute 'append'

### 병합과 조인

In [ ]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [ ]:
df2 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [ ]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장': ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [ ]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [ ]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과' , '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목': ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [ ]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [ ]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [ ]:
pd.merge(df1, df6, left_on='학생', right_on="이름")

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [ ]:
pd.merge(df1, df6, left_on='학생', right_on="이름").drop("이름", axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [ ]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [ ]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [ ]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [ ]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [ ]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                    '주문음식': ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [ ]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유신'],
                    '주문음료': ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [ ]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [ ]:
pd.merge(df7, df8, how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [ ]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [ ]:
pd.merge(df7, df8, how='left')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [ ]:
pd.merge(df7, df8, how='right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [ ]:
df9 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [ ]:
df10 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                     '순위': [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [ ]:
pd.merge(df9, df10, on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [ ]:
pd.merge(df9, df10, on='이름', suffixes=['_인기', '_성적'])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)

* `count`: 전체 개수
* `head`, `tail`: 앞의 항목 일부 반환, 뒤의 항목 일부 반환
* `describe`: Series, DataFrame의 각 컬럼에 대한 요약 통계
* `min`, `max`: 최소값, 최대값
* `cummin`, `cummax`: 누적 최소값, 누적 최대값
* `argmin`, `argmax`: 최소값과 최대값의 색인 위치
* `idxmin`, `idxmax`: 최소값과 최대값의 색인값
* `mean`, `median`: 평균값, 중앙값
* `std`, `var`: 표준편차(Standard Deviation), 분산(Variance)
* `skew`: 왜도(skewness) 값 계산
* `kurt`: 첨도(jurtosis) 값 계산
* `mad`: 절대 평균 편차(Mean Absolute Deviation)
* `sum`, `cumsum`: 전체 항목 합, 누적합
* `prod`, `cvumprod`: 전체 항목 곱, 누적곱
* `quantile`: 0부터 1까지의 분위수 계산
* `diff`: 1차 산술차 계산
* `pct_change`: 퍼센트 변화율 계산
* `corr`, `cov`: 상관관계, 공분산 계산


In [2]:
df = pd.DataFrame([[1, 1.2, np.nan],
                   [2.4, 5.5, 4.2],
                   [np.nan, np.nan, np.nan],
                   [0.44, -3.1, -4.1]],
                  index=[1, 2, 3, 4],
                  columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [3]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [4]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [5]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [6]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [7]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [8]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [9]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [10]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [11]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [12]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [13]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [14]:
df.pct_change()

<ipython-input-14-b804940da547>:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df.pct_change()


A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [15]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [16]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [17]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [18]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [19]:
df['A'].value_counts()

A
1.00    1
2.40    1
0.44    1
Name: count, dtype: int64

### GroupBy 연산

In [25]:
df = pd.DataFrame({'c1':['a', 'a', 'b', 'b', 'c', 'd','b'],
                   'c2':['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                   'c3':np.random.randint(7),
                   'c4':np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   1  0.424906
1  a  B   1  0.627898
2  b  B   1  0.838458
3  b  A   1  0.612373
4  c  D   1  0.744972
5  d  C   1  0.578200
6  b  C   1  0.445647

In [26]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [28]:
df['c3'].groupby(df['c1']).mean()

c1
a    1.0
b    1.0
c    1.0
d    1.0
Name: c3, dtype: float64

In [29]:
df['c4'].groupby(df['c2']).std()

c2
A    0.132559
B    0.148889
C    0.093729
D         NaN
Name: c4, dtype: float64

In [31]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.424906
    B     0.627898
b   A     0.612373
    B     0.838458
    C     0.445647
c   D     0.744972
d   C     0.578200
Name: c4, dtype: float64

In [32]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.424906  0.627898       NaN       NaN
b   0.612373  0.838458  0.445647       NaN
c        NaN       NaN       NaN  0.744972
d        NaN       NaN  0.578200       NaN

In [35]:
df.groupby('c1').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [34]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2               
a  A   1.0  0.424906
   B   1.0  0.627898
b  A   1.0  0.612373
   B   1.0  0.838458
   C   1.0  0.445647
c  D   1.0  0.744972
d  C   1.0  0.578200

In [36]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [37]:
for c1, group in df.groupby('c1'):
  print(c1)
  print(group)

a
  c1 c2  c3        c4
0  a  A   1  0.424906
1  a  B   1  0.627898
b
  c1 c2  c3        c4
2  b  B   1  0.838458
3  b  A   1  0.612373
6  b  C   1  0.445647
c
  c1 c2  c3        c4
4  c  D   1  0.744972
d
  c1 c2  c3      c4
5  d  C   1  0.5782


In [38]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
  print((c1, c2))
  print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   1  0.424906
('a', 'B')
  c1 c2  c3        c4
1  a  B   1  0.627898
('b', 'A')
  c1 c2  c3        c4
3  b  A   1  0.612373
('b', 'B')
  c1 c2  c3        c4
2  b  B   1  0.838458
('b', 'C')
  c1 c2  c3        c4
6  b  C   1  0.445647
('c', 'D')
  c1 c2  c3        c4
4  c  D   1  0.744972
('d', 'C')
  c1 c2  c3      c4
5  d  C   1  0.5782


In [39]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.424906
   B   0.627898
b  A   0.612373
   B   0.838458
   C   0.445647
c  D   0.744972
d  C   0.578200

In [40]:
df.groupby('c1')['c3'].quantile()

c1
a    1.0
b    1.0
c    1.0
d    1.0
Name: c3, dtype: float64

In [41]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [42]:
df.groupby('c1')['c4'].median()

c1
a    0.526402
b    0.612373
c    0.744972
d    0.578200
Name: c4, dtype: float64

In [43]:
df.groupby('c1')['c4'].std()

c1
a    0.143537
b    0.197152
c         NaN
d         NaN
Name: c4, dtype: float64

In [44]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.424906  0.424906  0.424906
   B   0.627898  0.627898  0.627898
b  A   0.612373  0.612373  0.612373
   B   0.838458  0.838458  0.838458
   C   0.445647  0.445647  0.445647
c  D   0.744972  0.744972  0.744972
d  C   0.578200  0.578200  0.578200

In [45]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean()

c1 c2        c4
0  a  A  0.424906
1  a  B  0.627898
2  b  A  0.612373
3  b  B  0.838458
4  b  C  0.445647
5  c  D  0.744972
6  d  C  0.578200

In [46]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.424906
    B     0.627898
b   A     0.612373
    B     0.838458
    C     0.445647
c   D     0.744972
d   C     0.578200
Name: c4, dtype: float64

In [48]:
def top(df, n=3, column='c1'):
  return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   1  0.838458
3  b  A   1  0.612373
6  b  C   1  0.445647
4  c  D   1  0.744972
5  d  C   1  0.578200

In [49]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   1  0.424906
   1  a  B   1  0.627898
b  2  b  B   1  0.838458
   3  b  A   1  0.612373
   6  b  C   1  0.445647
c  4  c  D   1  0.744972
d  5  d  C   1  0.578200

### 피벗 테이블(Pivot Table)

* `values`: 집계하려는 컬럼 이름 혹은 이름의 리스트. 기본적으로 모든 숫자 컬럼 집계
* `index`: 피벗테이블의 로우를 그룹으로 묶을 컬럼 이름이나 그룹 키
* `columns`: 피벗테이블의 컬럼을 그룹으로 묶을 컬럼 이름이나 그룹키
* `aggfunc`: 집계 함수나 함수 리스트. 기본값으로 `mean`이 사용
* `fill_value`: 결과 테이블에서 누락된 값 대체를 위한 값
* `dropna`: True인 경우 모든 항목이 NA인 컬럼은 포함하지 않음
* `margins`: 부분합이나 총계를 담기 위한 로우/컬럼 추가 여부. 기본값은 False




In [50]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   1.0  1.0  NaN  NaN  0.424906  0.627898       NaN       NaN
b   1.0  1.0  1.0  NaN  0.612373  0.838458  0.445647       NaN
c   NaN  NaN  NaN  1.0       NaN       NaN       NaN  0.744972
d   NaN  NaN  1.0  NaN       NaN       NaN  0.578200       NaN

In [51]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True)

c3                            c4                                        
c2     A    B    C    D  All         A         B         C         D       All
c1                                                                            
a    1.0  1.0  NaN  NaN  1.0  0.424906  0.627898       NaN       NaN  0.526402
b    1.0  1.0  1.0  NaN  1.0  0.612373  0.838458  0.445647       NaN  0.632159
c    NaN  NaN  NaN  1.0  1.0       NaN       NaN       NaN  0.744972  0.744972
d    NaN  NaN  1.0  NaN  1.0       NaN       NaN  0.578200       NaN  0.578200
All  1.0  1.0  1.0  1.0  1.0  0.518639  0.733178  0.511924  0.744972  0.610351

In [52]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum)

<ipython-input-52-3bc732ce229c>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],
<ipython-input-52-3bc732ce229c>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],
<ipython-input-52-3bc732ce229c>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],


c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    1.0  1.0  NaN  NaN   2  0.424906  0.627898       NaN       NaN  1.052804
b    1.0  1.0  1.0  NaN   3  0.612373  0.838458  0.445647       NaN  1.896478
c    NaN  NaN  NaN  1.0   1       NaN       NaN       NaN  0.744972  0.744972
d    NaN  NaN  1.0  NaN   1       NaN       NaN  0.578200       NaN  0.578200
All  2.0  2.0  2.0  1.0   7  1.037279  1.466357  1.023847  0.744972  4.272455

In [53]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum,
               fill_value=0)

<ipython-input-53-c5aeffa266cf>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],
<ipython-input-53-c5aeffa266cf>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],
<ipython-input-53-c5aeffa266cf>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(['c3', 'c4'],


c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    1.0  1.0  0.0  0.0   2  0.424906  0.627898  0.000000  0.000000  1.052804
b    1.0  1.0  1.0  0.0   3  0.612373  0.838458  0.445647  0.000000  1.896478
c    0.0  0.0  0.0  1.0   1  0.000000  0.000000  0.000000  0.744972  0.744972
d    0.0  0.0  1.0  0.0   1  0.000000  0.000000  0.578200  0.000000  0.578200
All  2.0  2.0  2.0  1.0   7  1.037279  1.466357  1.023847  0.744972  4.272455

In [54]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [57]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)

<ipython-input-57-c8f3cb868eed>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)
<ipython-input-57-c8f3cb868eed>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)
<ipython-input-57-c8f3cb868eed>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, 

c2     A    B    C    D  All
c1                          
a    1.0  1.0  NaN  NaN    2
b    1.0  1.0  1.0  NaN    3
c    NaN  NaN  NaN  1.0    1
d    NaN  NaN  1.0  NaN    1
All  2.0  2.0  2.0  1.0    7

### 범주형(Categorical) 데이터

* `add_categories`: 기존 카테고리에 새로운 카테고리 추가
* `as_ordered`: 카테고리에 순서 지정
* `as_unordered`: 카테고리에 순서 미지정
* `remove_categories`: 카테고리 제거
* `remove_unused_categories`: 사용안하는 카테고리 제거
* `rename_categores`: 카테고리 이름 변경
* `reorder_categories`: 새로운 카테고리에 순서 지정
* `set_categories`: 새로운 카테고리로 변경


In [ ]:
2:39:06~부터 듣기

## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly